
name: my_exam_Dillen-van-der-Merwe

 

on:
  push:
    branches:
      - main

 

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

 

      - name: Install dependencies
        run: npm install

 

      - name: Build
        run: npm run build

 

      - name: Test
        run: npm run test

 

      - name: Deploy to Staging
        run: npm run deploy

 
